version: '3.3'
services:

  db:
    container_name: user-auth
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'alfred'
      MYSQL_USER: 'alfred'
      MYSQL_PASSWORD: 'alfred_psw'
      MYSQL_ROOT_PASSWORD: 'root_pasw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - sail


volumes:
  my-db:

networks:
  sail:
    driver: bridge

